name = "openshop"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration for serving React build
[assets]
directory = "dist"
binding = "ASSETS"

# KV namespace binding
[[kv_namespaces]]
binding = "OPENSHOP_KV"
id = "" # This will be set during setup

# Environment variables
[vars]
SITE_URL = "" # This will be set during setup

# Secrets (set via wrangler secret put)
# STRIPE_SECRET_KEY
# VITE_STRIPE_PUBLISHABLE_KEY  
# ADMIN_PASSWORD
