name = "openshop-test3"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration for serving React build
[assets]
directory = "dist"
binding = "ASSETS"

# Environment variables
[vars]
SITE_URL = "https://openshop-test3.workers.dev" # This will be set during setup


# KV namespace binding
[[kv_namespaces]]
binding = "OPENSHOP-TEST3_KV"
id = "3ccaf8edbb1a44edb897087d970b72f1"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.