// Centralized configuration
import { CORS_ORIGINS, getCorsOrigins, CORS_ALLOWED_METHODS, CORS_ALLOWED_HEADERS, SHIPPING_COUNTRIES, ALLOWED_DRIVE_HOSTS, ADMIN_TOKEN_TTL, ADMIN_TOKEN_TTL_MS, KV_KEYS, THEME_COLOR_KEYS, THEME_RADIUS_MULTIPLIER_MIN, THEME_RADIUS_MULTIPLIER_MAX } from './constants.js'
import { validateEnv, getEnv } from './env.js'

export {
  CORS_ORIGINS,
  getCorsOrigins,
  CORS_ALLOWED_METHODS,
  CORS_ALLOWED_HEADERS,
  SHIPPING_COUNTRIES,
  ALLOWED_DRIVE_HOSTS,
  ADMIN_TOKEN_TTL,
  ADMIN_TOKEN_TTL_MS,
  KV_KEYS,
  THEME_COLOR_KEYS,
  THEME_RADIUS_MULTIPLIER_MIN,
  THEME_RADIUS_MULTIPLIER_MAX,
  validateEnv,
  getEnv,
}

